server:
  port: 88

#配置网关
spring:
  cloud:
    #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    #gateway配置
    gateway:
      routes:
#        - id: guonei_route
#          uri: http://news.baidu.com
#          predicates:
#            - Path=/guonei   # http://news.baidu.com/guonei
#
#        - id: guoji_route
#          uri: http://news.baidu.com
#          predicates:
#            - Path=/guoji   # http://news.baidu.com/guoji

        #路径比较精确的放在上面，防止被转发走
        #商品网关
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} #重写路径
          ## 前端发的：http://localhost:88/api/product/category/list/tree，后台要接收的：http://localhost:10000/product/category/list/tree，需要路径重写

        #第三方服务网关
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment} #重写路径
          ## 前端发的：http://localhost:88/api/thirdparty/oss/policy，后台要接收的：http://localhost:30000/oss/policy，需要路径重写

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #重写路径
          ## 前端发的：http://localhost:88/api/captcha.jpg，后台要接收的：http://localhost:8080/renren-fast/captcha.jpg，需要路径重写

