server:
  port: 88

#配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: guonei_route
          uri: http://news.baidu.com
          predicates:
            - Path=/guonei   # http://news.baidu.com/guonei

        - id: guoji_route
          uri: http://news.baidu.com
          predicates:
            - Path=/guoji   # http://news.baidu.com/guoji

